### ISSUE TITLE
Only for EE?

### ISSUE THREAD

**Issue by clicktrend** [marellocommerce/magento2-marello-bridge#3]
Hello,

I am not able to run your code in Magento CE. You are using RMA classes which I cannot find like

    Magento\Rma\Model\RmaRepository
    Magento\Rma\Model\ResourceModel\Item\Collection
    Magento\Rma\Model\ResourceModel\Item\CollectionFactory

Is this a EE Module?

**Comment by clicktrend** [comment]
Have a look at https://github.com/magento/magento2/issues/5710
Maybe that's the reason why it was locked at "100.0.*" #2

**Comment by 24198** [comment]
Hi @clicktrend,

It isn't suppose to be only for EE, we developed the extension on an EE instance, which is probably why RMA is still in there. Currently we're extracting the EE code from this repo. This will be available shortly.

Thanks for reporting!


Kind Regards,


Jaimy Casteleijn

**Comment by clicktrend** [comment]
I have created dummy RMA classes in my project directory. Compiling is possible now.

**Comment by 24198** [comment]
Hi @clicktrend,

We've removed the references to the EE code in the current master branch. Took a little longer than expected though, I'm sorry for the delay.

Kind Regards,


Jaimy Casteleijn
