### ISSUE TITLE
Module sequence

### ISSUE THREAD

**Issue by clicktrend** [marellocommerce/magento2-marello-bridge#5]
Add sequence Magento_Sales to module.xml to ensure your module is loaded after Magento_Sales.

    <sequence>
        <module name="Magento_Sales"/>
     </sequence>

**Comment by 24198** [comment]
Hi @clicktrend,

Updated the sequence as suggested in the current master branch. Thanks for reporting!


Kind Regards,


Jaimy Casteleijn
