### ISSUE TITLE
Workflow in order not exposed

### ISSUE THREAD

**Issue by clicktrend** [marellocommerce/magento2-marello-bridge#8]
Update order fails because of [not exposed workflow](https://github.com/marellocommerce/marello/issues/21).  Error at [line 77](https://github.com/marellocommerce/magento2-marello-bridge/blob/master/Model/Processor/UpdateOrderProcessor.php#L77).

**Comment by 24198** [comment]
Hi,

This issue is fixed in the Release of 1.0.0 of the Bridge. I'm closing the issue for now.
Thanks for reporting!
